### PR TITLE
Remove unused data and unnecessary queries

### PR DESCRIPTION
**Pull request by ivanceras**

### CODE REVIEW

**Comment by ivanceras** [comment]
Fix https://github.com/mcux/kylyp/issues/21

**Comment by krircc** [comment]
@ivanceras can you give it a try, the sql have a different result.  the result no comment content about that article.

**Comment by krircc** [comment]
i will try to use sql but not *

**Comment by ivanceras** [comment]
Ok, we might need to put it back, but it looks like article content has been extracted several times. This should be like a tree

```rust
Article{
  cooked: String,
  comments: Vec<Comment>
}
```

Also, this one looks like a copy pasting of the fields of article
```rust
#[derive(Debug,Serialize)]
pub struct UserComment {
    pub id: i32,
    pub aid: i32,
    pub uid: i32,
    pub raw: String,
    pub cooked: String,
    pub created_at: DateTime<Utc>,
    pub rtime: String,
    pub article_id: i32,
    pub article_uid: i32,
    pub article_category: String,
    pub article_status: i32,
    pub article_comments_count: i32,
    pub article_title: String,
    pub article_raw: String,
    pub article_cooked: String,
    pub article_created_at: DateTime<Utc>,
    pub article_updated_at: DateTime<Utc>,
}
```
Shouldn't this be structured like this?
```rust
#[derive(Debug,Serialize)]
pub struct UserComment {
    pub id: i32,
    pub aid: i32,
    pub uid: i32,
    pub raw: String,
    pub cooked: String,
    pub created_at: DateTime<Utc>,
    pub article<Article>
}
````
You can still access the article data in the template using
```
user_comment.article.cooked
```

**Comment by krircc** [comment]
@ivanceras ok i will do this

**Pull request merged**
